### ISSUE TITLE
only API usage possible? 

### ISSUE THREAD

**Issue by codeagencybe** [isotopsweden/wp-imgix-helper#1]
Hello,

Can this plugin be used only for API usage without IMGIX CDN? 
I'm looking for a way to manipulate only specific images (product images for WooCommerce) and download them back to Wordpress. 
Images need to be made square, fit and fill with bg color, but only for WooCommerce images!

We use amazon S3 + our own CDN, I only need IMGIX to manipulate the images. 
I'm looking all around, but can not find anything that is suitable. 
Now I just stumble on your plugin, so can you please kindly elaborate what is possible with your plugin please? 

Thanks!

**Comment by frozzare** [comment]
Hi,

No, this is not a plugin for API usages.

It's only a helper plugin for https://github.com/imgix-wordpress/images-via-imgix with over changes. 

I don't have any recommendation for another plugin or package.
